[config]
hostname = "127.0.0.1:6667"
nickname = "marvy"
channel = "#acme"
broker = "localhost:9092"
topic = "MARV.MESSAGES"
group = "MARV"
messages_log = "messages.txt"
database_url = "postgres://deploy42:deploy42@localhost:5432/deploy42"
